ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:11.1.1
FROM $BUILD_FROM

# Install requirements for add-on
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

ARG BUILD_ARCH=amd64

WORKDIR /app

COPY . /app
COPY ./front/requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

RUN \
    ARCH="${BUILD_ARCH}" \
    && if [[ "${BUILD_ARCH}" = "aarch64" ]]; then ARCH="arm64"; fi \
    && if [[ "${BUILD_ARCH}" = "armhf" ]]; then ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "armv7" ]]; then ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "i386" ]]; then ARCH="386"; fi \
    && wget -O /usr/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-$ARCH \
    && chmod +x /usr/bin/cloudflared

CMD ["python","app.py"]