ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:11.1.1
FROM $BUILD_FROM

RUN \
    apk add --no-cache --virtual .build-dependencies \
    \
    && apk add --no-cache \
    nginx \
    nodejs \
    openssl \
    yarn

ARG BUILD_ARCH=amd64
RUN \
    ARCH="${BUILD_ARCH}" \
    && if [[ "${BUILD_ARCH}" = "aarch64" ]]; then ARCH="arm64"; fi \
    && if [[ "${BUILD_ARCH}" = "armhf" ]]; then ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "armv7" ]]; then ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "i386" ]]; then ARCH="386"; fi \
    && wget -O /usr/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-$ARCH \
    && chmod +x /usr/bin/cloudflared

COPY web/nginx.conf /etc/nginx/http.d/default.conf

WORKDIR /app
COPY web/package*.json ./
RUN yarn global add @quasar/cli
COPY web/ .

RUN yarn
RUN quasar build

COPY web/dist/spa /var/www/dist/spa
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]