ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:11.1.1
FROM $BUILD_FROM

RUN \
    apk add --no-cache --virtual .build-dependencies \
    \
    && apk add --no-cache \
    nginx=1.20.2-r0 \
    nodejs=16.14.0-r \
    openssl=1.1.1n-r0 \
    yarn=1.22.17-r0

ARG BUILD_ARCH=amd64

WORKDIR /app

COPY ./front /app

RUN pip install -r /app/requirements.txt

RUN \
    ARCH="${BUILD_ARCH}" \
    && if [[ "${BUILD_ARCH}" = "aarch64" ]]; then ARCH="arm64"; fi \
    && if [[ "${BUILD_ARCH}" = "armhf" ]]; then ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "armv7" ]]; then ARCH="arm"; fi \
    && if [[ "${BUILD_ARCH}" = "i386" ]]; then ARCH="386"; fi \
    && wget -O /usr/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-$ARCH \
    && chmod +x /usr/bin/cloudflared

CMD ["python","app.py"]